baseURL = "https://www.awesomestuff.dev/"
languageCode = "en-us"
title = "Awesome Stuff"
disableKinds = ["taxonomy","taxonomyTerm"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = "A curated list of awesome resources for developers in ðŸ‡²ðŸ‡¾ Malaysia."
  ogimage = "/img/og.png"
  keywords = []